import isNullOrEmpty from "~~/isNullOrEmpty";
import axios from "axios";
let url = process.env.NODE_ENV === 'production' ? "https://api.daney.app/" : 'http://localhost:5000/';
import { Configuration } from "~~/services/autogenerated/V1/configuration";

export function getSwaggerAxiosOptions(): Configuration {
    return {
        basePath: new URL(url).origin,
        accessToken: async () => {
            let token;
            if (isNullOrEmpty(localStorage.getItem("tokenStorage"))) {
                token = await getNewToken();
            } else {
                try {
                    token = await validateToken();
                } catch (e) {
                    token = await getNewToken();
                }
            }
            return token;
        },
        isJsonMime: (mime: string) => {
            const jsonMime = new RegExp('^(application\/json|[^;/ \t]+\/[^;/ \t]+[+]json)[ \t]*(;.*)?$', 'i');
            return mime !== null && (jsonMime.test(mime) || mime.toLowerCase() === 'application/json-patch+json');
        }
    };
}

let validateTokenPromise: Promise<string> | null = null;

async function validateToken(): Promise<string> {
    const token = () => {
        return localStorage.getItem("tokenStorage");
    };
    if (validateTokenPromise === null) {
        validateTokenPromise = new Promise((resolve, reject) => {
            const tmpToken = token();
            if (isNullOrEmpty(tmpToken)) {
                reject(new Error("No token"));
                return;
            }

            axios.post(`${url}api/v1.0/auth/validate-token`, {},
                {
                    headers: {"Authorization": "Bearer " + tmpToken}
                },
            ).then(() => {
                let token: string | null = localStorage.getItem("tokenStorage");
                resolve(token ? token : "");
                validateTokenPromise = null;
            }).catch((e) => {
                reject(e);
                validateTokenPromise = null;
            });
        });
    }

    return validateTokenPromise;
}

async function getNewToken(): Promise<string> {
    let bearerToken = (await axios({
        method: 'GET',
        url: `/api/token`,
    })).data;

    let token = (await axios({
        method: 'post',
        url: `${url}api/v1.0/auth/get-token`,
        params: {
            token: bearerToken,
        },
    })).data;

    axios.defaults.headers.common["Authorization"] = "Bearer " + token.token;

    localStorage.setItem("tokenStorage", token.token);
    return token.token;
}

export default defineNuxtPlugin(() => {
    return {
        provide: {
            getSwaggerAxiosOptions: () => getSwaggerAxiosOptions()
        }
    }
})
