<template>
    <div>
        <da-panel title="Verification System" :has-loading-icon="true" :is-loading="isLoading">
            <template #panel-top-actions>
                <button class="btn btn-primary">
                    Quick Setup
                </button>
                <button @click="save()" class="btn btn-orange">
                    Save
                </button>
            </template>
            <da-panel-tab v-if="categories.length > 0" name="Verification Categories" id-field="categories">
                <div class="grid grid-cols-2 gap-5">
                    <template v-for="category in categories">
                        <div class="flex-1 basis-1/2 min-w-[250px]">
                            <sim-select :title="category.Name" v-model="category.Value" :help-text="category.HelpText"
                                        :options="categoriesOptions" />
                        </div>
                    </template>
                </div>
            </da-panel-tab>
            <da-panel-tab v-if="channels.length > 0" name="Verification Channels" id-field="channels">
                <div class="grid grid-cols-2 gap-5">
                    <template v-for="channel in channels">
                        <div>
                            <sim-select :title="channel.Name" v-model="channel.Value" :help-text="channel.HelpText"
                                        :options="channelsOptions" />
                        </div>
                    </template>
                </div>
            </da-panel-tab>
            <da-panel-tab v-if="roles.length > 0" name="Verification Roles" id-field="roles">
                <div class="grid grid-cols-2 gap-5">
                    <template v-for="role in roles">
                        <div>
                            <sim-select :title="role.Name" v-model="role.Value" :help-text="role.HelpText"
                                        :options="rolesOptions"/>
                        </div>
                    </template>
                </div>
            </da-panel-tab>
            <da-panel-tab v-if="textParagraphs.length > 0 || texts.length > 0" name="Verification Texts"
                          id-field="texts" icon="fa-solid fa-server">
                <div class="grid grid-cols-2 gap-5" v-if="textParagraphs || texts">
                    <template v-if="textParagraphs" v-for="textParagraph in textParagraphs">
                        <div>
                            <sim-textarea v-model="textParagraph.Value" :title="textParagraph.Name"
                                          :max="textParagraph.PremiumFeature ? textParagraph.PremiumMaxLength : textParagraph.MaxLength"
                                          :help-text="textParagraph.HelpText"
                            />
                        </div>
                    </template>

                    <template v-if="texts" v-for="text in texts">
                        <div>
                            <sim-input v-model="text.Value" :title="text.Name"
                                       :max="text.PremiumFeature ? text.PremiumMaxLength : text.MaxLength"
                                       :help-text="text.HelpText"
                            />
                        </div>
                    </template>
                </div>
            </da-panel-tab>
            <da-panel-tab v-if="booleans.length > 0" name="Verification Settings" id-field="settings">
                <div class="grid grid-cols-2 gap-5">
                    <template v-for="boolean in booleans">
                        <div>
                            <label :for="boolean.UID">
                                {{ boolean.Name }}
                                <client-only>
                                    <u-tooltip arrow :popper="{ placement: 'top' }" class="inline-block!"
                                               :text="boolean.HelpText">
                                        <div>
                                            <font-awesome-icon icon="fa-solid fa-circle-question" fixed-width/>
                                        </div>
                                    </u-tooltip>
                                </client-only>
                            </label>
                            <input type="checkbox" :id="boolean.UID" v-model="boolean.Value"/>
                        </div>
                    </template>
                </div>
            </da-panel-tab>
        </da-panel>
    </div>
</template>

<script setup>
import {ref, onMounted} from "vue";

import {useNuxtApp} from "nuxt/app";

import {DiscordCategoryApi} from "~~/services/autogenerated/V1/api/discord-category-api";
import {DiscordChannelApi} from "~~/services/autogenerated/V1/api/discord-channel-api";
import {DiscordRoleApi} from "~~/services/autogenerated/V1/api/discord-role-api";
import {ServerKeysBaseApi} from "~~/services/autogenerated/V1/api/server-keys-base-api";
import {ServerKeysApi} from "~~/services/autogenerated/V1/api/server-keys-api";
import DaPanel from "~/components/shared/da-panel/da-panel.vue";
import DaPanelTab from "~/components/shared/da-panel/da-panel-tab.vue";

let props = defineProps({
    uids: {
        type: Array
    }
});

const {$getSwaggerAxiosOptions, $constants, $toast} = useNuxtApp()

let DiscordCategoryService = new DiscordCategoryApi($getSwaggerAxiosOptions());
let DiscordChannelService = new DiscordChannelApi($getSwaggerAxiosOptions());
let DiscordRoleService = new DiscordRoleApi($getSwaggerAxiosOptions());
let ServerKeysBaseService = new ServerKeysBaseApi($getSwaggerAxiosOptions());
let ServerKeysService = new ServerKeysApi($getSwaggerAxiosOptions());

let isLoading = ref(true);

let categoriesOptions = ref([]);
let channelsOptions = ref([]);
let rolesOptions = ref([]);

let serverKeys = ref([]);
let categories = ref([]);
let channels = ref([]);
let texts = ref([]);
let textParagraphs = ref([]);
let roles = ref([]);

let booleans = ref([]);

let route = useRoute();
async function getCategories() {
    categoriesOptions = (await DiscordCategoryService.getCategories({
        guildID: route.params.id,
    })).data;
}

async function getChannels() {
    channelsOptions = (await DiscordChannelService.getChannels({
        guildID: route.params.id,
    })).data;
}

async function getRoles() {
    rolesOptions = (await DiscordRoleService.getRoles({
        guildID: route.params.id,
    })).data;
}

async function getServerKeys() {
    serverKeys = (await ServerKeysBaseService.getAll({
        APIDaneyControllersServerKeyRequest: {
            GuildID: route.params.id,
            Types: [$constants.types.channel, $constants.types.category, $constants.types.role,
                $constants.types.text, $constants.types.textParagraph, $constants.types.boolean],
            Uids: props.uids
        },
    })).data;
    for (let i = 0; i < serverKeys.length; i++) {
        if (serverKeys[i].Type === $constants.types.category) categories.value.push(serverKeys[i]);
        if (serverKeys[i].Type === $constants.types.channel) channels.value.push(serverKeys[i]);
        if (serverKeys[i].Type === $constants.types.textParagraph) textParagraphs.value.push(serverKeys[i]);
        if (serverKeys[i].Type === $constants.types.text) texts.value.push(serverKeys[i]);
        if (serverKeys[i].Type === $constants.types.role) roles.value.push(serverKeys[i]);
        if (serverKeys[i].Type === $constants.types.boolean) booleans.value.push(serverKeys[i]);
    }

    setTimeout(() => {
        isLoading.value = false;
    }, 2000);
}

onMounted(async () => {
    let getCategoriesTask = ref(getCategories());
    let getChannelsTask = ref(getChannels());
    let getRolesTask = ref(getRoles());
    let getServerKeysTask = ref(getServerKeys());

    await Promise.all([getCategoriesTask, getChannelsTask, getRolesTask, getServerKeysTask]);
});

async function save() {
    try {
        let values = [
            ...categories._rawValue,
            ...channels._rawValue,
            ...textParagraphs._rawValue,
            ...texts._rawValue,
            ...roles._rawValue,
            ...booleans._rawValue
        ];

        values = values.map((item) => {
            return {
                UID: item.UID,
                Value: item.Value,
            }
        });

        await ServerKeysService.upsertall({
            guildID: route.params.id,
            APIDaneyRepositoriesEntitiesServerKeyRequester: values,
        });

        $toast({type: "success", text: "Settings saved successfully!", header: "Success"});
    } catch (error) {
        $toast({type: "error", text: "Failed to save settings. Please try again.", header: "Error"});
        console.error("Save error:", error);
    }
}
</script>

