<style scoped lang="scss">

</style>

<template>
    <div>
        <coming-soon/>
        <da-panel title="Leveling" :has-loading-icon="true">
            <template #panel-top-actions>
                <button @click="openModal" class="btn btn-primary">
                    Save
                </button>
            </template>
            <da-panel-tab name="Leveling Settings" id-field="main" icon="server">
                <div class="row">
                    <div class="col-12 col-sm-6">
                        <sim-timezone :settings="timezoneSettings" title="Timezone for weekend xp"
                                      v-model="timezoneInt"/>
                    </div>
                    <div class="col-12 col-sm-6">
                        <span class="mt-1 d-block">Your time: {{ time }}</span>
                    </div>
                </div>
            </da-panel-tab>
        </da-panel>
        <da-confirm-modal v-model="timezoneModal" 
                          description="You will have 5 minutes to change timezone after you have committed the timezone, so if you made a mistake you can change it. After that it will be set for a week." 
                          :action="confirm" ok-text="Set TimeZone"/>
    </div>
</template>

<script lang="ts">
definePageMeta({
    layout: "user",
});

import {UserApi} from "~/services/autogenerated/V1/api/user-api";

let advancedFormat = require('dayjs/plugin/advancedFormat')
let utc = require('dayjs/plugin/utc');
let tz = require('dayjs/plugin/timezone');

export default {
    name: "leveling",
    layout: "user",
    data() {
        return {
            UserService: new UserApi(this.$store.getters.swaggerAxiosOptions),
            timezoneModal: false,
            user: null,
            timezoneInt: -1,
            timezone: {id: -1, text: ""},
            time: 'Not chosen.',
            timezoneSettings: {
                placeholder: "Choose your timezone",
            },
        }
    },
    methods: {
        openModal() {
            if(this.timezoneInt == -1) {
                this.$toast.error('Choose your timezone');
                return;
            }
            
            let time = this.$dayjs();
            let last = this.$dayjs(this.user.TimeZoneLastChange);
            let fiveMinutes = last.clone().add(1, 'm');
            let week = last.clone().add(1, 'w');
            
            if(time.isAfter(fiveMinutes) && time.isBefore(week)) {
                this.$toast.error(`You cannot update the timezone till: Starting with day: ${this.$dayjs(week).tz(this.timezone.text).format('DD-MM-YYYY HH:mm:ss z')}.`);
                return;
            }
            
            this.timezoneModal = true;
        },
        confirm() {
            this.ok();
        },
        async ok() {
            await this.UserService.setTimeZone(
                {
                    userID: this.$auth.user.id,
                    timezone: this.timezoneInt
                }
            );
        },
        getTime() {
            this.$dayjs.extend(utc);
            this.$dayjs.extend(tz);
            this.$dayjs.extend(advancedFormat);
            if (this.timezone.id === -1) return;
            this.time = 'Starting with day: ' + this.$dayjs().tz(this.timezone.text).format('DD-MM-YYYY HH:mm:ss z');
        },
        getTimezone(int) {
            for (let i = 0; i < this.$const.zones.length; i++) {
                if (this.$const.zones[i].id === Number(int)) {
                    this.timezone = this.$const.zones[i];
                    break;
                }
            }
        }
    },
    watch: {
        timezoneInt: function (val, oldVal) {
            this.getTimezone(val);
            this.getTime();
        },
    },
    async mounted() {
        this.user = (await this.UserService.getSingle({
            userID: this.$auth.user.id,
        })).data;

        if (this.user != null && this.user.TimeZone != null) {
            this.timezoneInt = this.user.TimeZone;
        }

        for (let i = 0; i < this.$const.zones.length; i++) {
            this.timezone = this.$const.zones[i];
        }
        
        /*this.timezoneModal = true;*/
    }
}
</script>