/* tslint:disable */
/* eslint-disable */
/**
 * Daney API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIDaneyModelsCommonSelectItem } from '../models';
/**
 * DiscordRoleApi - axios parameter creator
 */
export const DiscordRoleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [guildID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoles: async (guildID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1.0/discordrole/get-roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (guildID !== undefined) {
                localVarQueryParameter['guildID'] = guildID;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DiscordRoleApi - functional programming interface
 */
export const DiscordRoleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DiscordRoleApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [guildID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRoles(guildID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<APIDaneyModelsCommonSelectItem>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRoles(guildID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DiscordRoleApi.getRoles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DiscordRoleApi - factory interface
 */
export const DiscordRoleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DiscordRoleApiFp(configuration)
    return {
        /**
         * 
         * @param {DiscordRoleApiGetRolesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoles(requestParameters: DiscordRoleApiGetRolesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<APIDaneyModelsCommonSelectItem>> {
            return localVarFp.getRoles(requestParameters.guildID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getRoles operation in DiscordRoleApi.
 */
export interface DiscordRoleApiGetRolesRequest {
    readonly guildID?: string
}

/**
 * DiscordRoleApi - object-oriented interface
 */
export class DiscordRoleApi extends BaseAPI {
    /**
     * 
     * @param {DiscordRoleApiGetRolesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRoles(requestParameters: DiscordRoleApiGetRolesRequest = {}, options?: RawAxiosRequestConfig) {
        return DiscordRoleApiFp(this.configuration).getRoles(requestParameters.guildID, options).then((request) => request(this.axios, this.basePath));
    }
}

