/* tslint:disable */
/* eslint-disable */
/**
 * Daney API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIDaneyModelsAuthGetTokenResponse } from '../models';
/**
 * DiscordGuildApi - axios parameter creator
 */
export const DiscordGuildApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Array<number>} [request_body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checks: async (request_body?: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1.0/discordguild/checks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request_body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DiscordGuildApi - functional programming interface
 */
export const DiscordGuildApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DiscordGuildApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {Array<number>} [request_body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checks(request_body?: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<APIDaneyModelsAuthGetTokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checks(request_body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DiscordGuildApi.checks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DiscordGuildApi - factory interface
 */
export const DiscordGuildApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DiscordGuildApiFp(configuration)
    return {
        /**
         * 
         * @param {DiscordGuildApiChecksRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checks(requestParameters: DiscordGuildApiChecksRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<APIDaneyModelsAuthGetTokenResponse> {
            return localVarFp.checks(requestParameters.request_body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for checks operation in DiscordGuildApi.
 */
export interface DiscordGuildApiChecksRequest {
    readonly request_body?: Array<number>
}

/**
 * DiscordGuildApi - object-oriented interface
 */
export class DiscordGuildApi extends BaseAPI {
    /**
     * 
     * @param {DiscordGuildApiChecksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public checks(requestParameters: DiscordGuildApiChecksRequest = {}, options?: RawAxiosRequestConfig) {
        return DiscordGuildApiFp(this.configuration).checks(requestParameters.request_body, options).then((request) => request(this.axios, this.basePath));
    }
}

