/* tslint:disable */
/* eslint-disable */
/**
 * Daney API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIDaneyModelsAuthGetTokenResponse } from '../models';
/**
 * GuildApi - axios parameter creator
 */
export const GuildApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [guildID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingle: async (guildID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1.0/guild/get-single`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (guildID !== undefined) {
                localVarQueryParameter['guildID'] = guildID;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GuildApi - functional programming interface
 */
export const GuildApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GuildApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [guildID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSingle(guildID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<APIDaneyModelsAuthGetTokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSingle(guildID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GuildApi.getSingle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GuildApi - factory interface
 */
export const GuildApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GuildApiFp(configuration)
    return {
        /**
         * 
         * @param {GuildApiGetSingleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingle(requestParameters: GuildApiGetSingleRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<APIDaneyModelsAuthGetTokenResponse> {
            return localVarFp.getSingle(requestParameters.guildID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getSingle operation in GuildApi.
 */
export interface GuildApiGetSingleRequest {
    readonly guildID?: string
}

/**
 * GuildApi - object-oriented interface
 */
export class GuildApi extends BaseAPI {
    /**
     * 
     * @param {GuildApiGetSingleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSingle(requestParameters: GuildApiGetSingleRequest = {}, options?: RawAxiosRequestConfig) {
        return GuildApiFp(this.configuration).getSingle(requestParameters.guildID, options).then((request) => request(this.axios, this.basePath));
    }
}

