/* tslint:disable */
/* eslint-disable */
/**
 * Daney API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIDaneySharedModelsPagedListOfDaneyDataAccessEntitiesModerationLogging } from '../models';
/**
 * ModerationLoggingApi - axios parameter creator
 */
export const ModerationLoggingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [guildID] 
         * @param {number} [type] 
         * @param {string} [sort] 
         * @param {string} [order] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPaged: async (guildID?: number, type?: number, sort?: string, order?: string, limit?: number, offset?: number, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1.0/moderationlogging/get-paged`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (guildID !== undefined) {
                localVarQueryParameter['guildID'] = guildID;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ModerationLoggingApi - functional programming interface
 */
export const ModerationLoggingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ModerationLoggingApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [guildID] 
         * @param {number} [type] 
         * @param {string} [sort] 
         * @param {string} [order] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPaged(guildID?: number, type?: number, sort?: string, order?: string, limit?: number, offset?: number, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<APIDaneySharedModelsPagedListOfDaneyDataAccessEntitiesModerationLogging>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPaged(guildID, type, sort, order, limit, offset, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationLoggingApi.getPaged']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ModerationLoggingApi - factory interface
 */
export const ModerationLoggingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ModerationLoggingApiFp(configuration)
    return {
        /**
         * 
         * @param {ModerationLoggingApiGetPagedRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPaged(requestParameters: ModerationLoggingApiGetPagedRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<APIDaneySharedModelsPagedListOfDaneyDataAccessEntitiesModerationLogging> {
            return localVarFp.getPaged(requestParameters.guildID, requestParameters.type, requestParameters.sort, requestParameters.order, requestParameters.limit, requestParameters.offset, requestParameters.search, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getPaged operation in ModerationLoggingApi.
 */
export interface ModerationLoggingApiGetPagedRequest {
    readonly guildID?: number

    readonly type?: number

    readonly sort?: string

    readonly order?: string

    readonly limit?: number

    readonly offset?: number

    readonly search?: string
}

/**
 * ModerationLoggingApi - object-oriented interface
 */
export class ModerationLoggingApi extends BaseAPI {
    /**
     * 
     * @param {ModerationLoggingApiGetPagedRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPaged(requestParameters: ModerationLoggingApiGetPagedRequest = {}, options?: RawAxiosRequestConfig) {
        return ModerationLoggingApiFp(this.configuration).getPaged(requestParameters.guildID, requestParameters.type, requestParameters.sort, requestParameters.order, requestParameters.limit, requestParameters.offset, requestParameters.search, options).then((request) => request(this.axios, this.basePath));
    }
}

