/* tslint:disable */
/* eslint-disable */
/**
 * Daney API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIDaneyControllersServerKeyRequest } from '../models';
// @ts-ignore
import type { APIDaneyModelsServerKeysServerKeyModel } from '../models';
/**
 * ServerKeysBaseApi - axios parameter creator
 */
export const ServerKeysBaseApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {APIDaneyControllersServerKeyRequest} [APIDaneyControllersServerKeyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAll: async (APIDaneyControllersServerKeyRequest?: APIDaneyControllersServerKeyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1.0/serverkeysbase/get-all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(APIDaneyControllersServerKeyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ServerKeysBaseApi - functional programming interface
 */
export const ServerKeysBaseApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ServerKeysBaseApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {APIDaneyControllersServerKeyRequest} [APIDaneyControllersServerKeyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAll(APIDaneyControllersServerKeyRequest?: APIDaneyControllersServerKeyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<APIDaneyModelsServerKeysServerKeyModel>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAll(APIDaneyControllersServerKeyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerKeysBaseApi.getAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ServerKeysBaseApi - factory interface
 */
export const ServerKeysBaseApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ServerKeysBaseApiFp(configuration)
    return {
        /**
         * 
         * @param {ServerKeysBaseApiGetAllRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAll(requestParameters: ServerKeysBaseApiGetAllRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<APIDaneyModelsServerKeysServerKeyModel>> {
            return localVarFp.getAll(requestParameters.APIDaneyControllersServerKeyRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAll operation in ServerKeysBaseApi.
 */
export interface ServerKeysBaseApiGetAllRequest {
    readonly APIDaneyControllersServerKeyRequest?: APIDaneyControllersServerKeyRequest
}

/**
 * ServerKeysBaseApi - object-oriented interface
 */
export class ServerKeysBaseApi extends BaseAPI {
    /**
     * 
     * @param {ServerKeysBaseApiGetAllRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAll(requestParameters: ServerKeysBaseApiGetAllRequest = {}, options?: RawAxiosRequestConfig) {
        return ServerKeysBaseApiFp(this.configuration).getAll(requestParameters.APIDaneyControllersServerKeyRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

