/* tslint:disable */
/* eslint-disable */
/**
 * Daney API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIDaneyRepositoriesEntitiesServerKey } from '../models';
// @ts-ignore
import type { APIDaneyRepositoriesEntitiesServerKeyRequester } from '../models';
/**
 * ServerKeysApi - axios parameter creator
 */
export const ServerKeysApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [guildID] 
         * @param {Array<string>} [request_body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getValues: async (guildID?: number, request_body?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1.0/serverkeys/get-values`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (guildID !== undefined) {
                localVarQueryParameter['guildID'] = guildID;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request_body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [guildID] 
         * @param {string} [uid] 
         * @param {string} [value] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (guildID?: number, uid?: string, value?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1.0/serverkeys/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (guildID !== undefined) {
                localVarQueryParameter['guildID'] = guildID;
            }

            if (uid !== undefined) {
                localVarQueryParameter['uid'] = uid;
            }

            if (value !== undefined) {
                localVarQueryParameter['value'] = value;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [guildID] 
         * @param {Array<APIDaneyRepositoriesEntitiesServerKeyRequester>} [APIDaneyRepositoriesEntitiesServerKeyRequester] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertall: async (guildID?: number, APIDaneyRepositoriesEntitiesServerKeyRequester?: Array<APIDaneyRepositoriesEntitiesServerKeyRequester>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1.0/serverkeys/upsertall`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (guildID !== undefined) {
                localVarQueryParameter['guildID'] = guildID;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(APIDaneyRepositoriesEntitiesServerKeyRequester, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ServerKeysApi - functional programming interface
 */
export const ServerKeysApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ServerKeysApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [guildID] 
         * @param {Array<string>} [request_body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getValues(guildID?: number, request_body?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<APIDaneyRepositoriesEntitiesServerKey>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getValues(guildID, request_body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerKeysApi.getValues']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [guildID] 
         * @param {string} [uid] 
         * @param {string} [value] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(guildID?: number, uid?: string, value?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(guildID, uid, value, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerKeysApi.update']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [guildID] 
         * @param {Array<APIDaneyRepositoriesEntitiesServerKeyRequester>} [APIDaneyRepositoriesEntitiesServerKeyRequester] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async upsertall(guildID?: number, APIDaneyRepositoriesEntitiesServerKeyRequester?: Array<APIDaneyRepositoriesEntitiesServerKeyRequester>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.upsertall(guildID, APIDaneyRepositoriesEntitiesServerKeyRequester, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerKeysApi.upsertall']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ServerKeysApi - factory interface
 */
export const ServerKeysApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ServerKeysApiFp(configuration)
    return {
        /**
         * 
         * @param {ServerKeysApiGetValuesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getValues(requestParameters: ServerKeysApiGetValuesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<APIDaneyRepositoriesEntitiesServerKey>> {
            return localVarFp.getValues(requestParameters.guildID, requestParameters.request_body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ServerKeysApiUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(requestParameters: ServerKeysApiUpdateRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.update(requestParameters.guildID, requestParameters.uid, requestParameters.value, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ServerKeysApiUpsertallRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertall(requestParameters: ServerKeysApiUpsertallRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.upsertall(requestParameters.guildID, requestParameters.APIDaneyRepositoriesEntitiesServerKeyRequester, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getValues operation in ServerKeysApi.
 */
export interface ServerKeysApiGetValuesRequest {
    readonly guildID?: number

    readonly request_body?: Array<string>
}

/**
 * Request parameters for update operation in ServerKeysApi.
 */
export interface ServerKeysApiUpdateRequest {
    readonly guildID?: number

    readonly uid?: string

    readonly value?: string
}

/**
 * Request parameters for upsertall operation in ServerKeysApi.
 */
export interface ServerKeysApiUpsertallRequest {
    readonly guildID?: number

    readonly APIDaneyRepositoriesEntitiesServerKeyRequester?: Array<APIDaneyRepositoriesEntitiesServerKeyRequester>
}

/**
 * ServerKeysApi - object-oriented interface
 */
export class ServerKeysApi extends BaseAPI {
    /**
     * 
     * @param {ServerKeysApiGetValuesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getValues(requestParameters: ServerKeysApiGetValuesRequest = {}, options?: RawAxiosRequestConfig) {
        return ServerKeysApiFp(this.configuration).getValues(requestParameters.guildID, requestParameters.request_body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ServerKeysApiUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public update(requestParameters: ServerKeysApiUpdateRequest = {}, options?: RawAxiosRequestConfig) {
        return ServerKeysApiFp(this.configuration).update(requestParameters.guildID, requestParameters.uid, requestParameters.value, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ServerKeysApiUpsertallRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public upsertall(requestParameters: ServerKeysApiUpsertallRequest = {}, options?: RawAxiosRequestConfig) {
        return ServerKeysApiFp(this.configuration).upsertall(requestParameters.guildID, requestParameters.APIDaneyRepositoriesEntitiesServerKeyRequester, options).then((request) => request(this.axios, this.basePath));
    }
}

