/* tslint:disable */
/* eslint-disable */
/**
 * Daney API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIDaneyModelsAuthGetTokenResponse } from '../models';
/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [userID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingle: async (userID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1.0/user/get-single`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (userID !== undefined) {
                localVarQueryParameter['userID'] = userID;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [userID] 
         * @param {number} [timezone] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setTimeZone: async (userID?: string, timezone?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1.0/user/set-time-zone`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (userID !== undefined) {
                localVarQueryParameter['userID'] = userID;
            }

            if (timezone !== undefined) {
                localVarQueryParameter['timezone'] = timezone;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [userID] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSingle(userID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<APIDaneyModelsAuthGetTokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSingle(userID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getSingle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [userID] 
         * @param {number} [timezone] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setTimeZone(userID?: string, timezone?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<APIDaneyModelsAuthGetTokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setTimeZone(userID, timezone, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.setTimeZone']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @param {UserApiGetSingleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingle(requestParameters: UserApiGetSingleRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<APIDaneyModelsAuthGetTokenResponse> {
            return localVarFp.getSingle(requestParameters.userID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UserApiSetTimeZoneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setTimeZone(requestParameters: UserApiSetTimeZoneRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<APIDaneyModelsAuthGetTokenResponse> {
            return localVarFp.setTimeZone(requestParameters.userID, requestParameters.timezone, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getSingle operation in UserApi.
 */
export interface UserApiGetSingleRequest {
    readonly userID?: string
}

/**
 * Request parameters for setTimeZone operation in UserApi.
 */
export interface UserApiSetTimeZoneRequest {
    readonly userID?: string

    readonly timezone?: number
}

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @param {UserApiGetSingleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSingle(requestParameters: UserApiGetSingleRequest = {}, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getSingle(requestParameters.userID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UserApiSetTimeZoneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public setTimeZone(requestParameters: UserApiSetTimeZoneRequest = {}, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).setTimeZone(requestParameters.userID, requestParameters.timezone, options).then((request) => request(this.axios, this.basePath));
    }
}

