/* tslint:disable */
/* eslint-disable */
/**
 * Daney API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface APIDaneyModelsServerKeysServerKeyModel {
    'UID'?: string;
    'Name'?: string | null;
    'HelpText'?: string | null;
    'Type'?: number;
    'GuildID'?: string;
    'Value'?: any | null;
    'MaxLength'?: number;
    'PremiumMaxLength'?: number;
    'Amount'?: number;
    'Required'?: boolean;
    'PremiumFeature'?: boolean;
}

