/* tslint:disable */
/* eslint-disable */
/**
 * Daney API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DaneyDataAccessEntitiesModerationLogging } from './daney-data-access-entities-moderation-logging';

export interface APIDaneySharedModelsPagedListOfDaneyDataAccessEntitiesModerationLogging {
    'rows'?: Array<DaneyDataAccessEntitiesModerationLogging> | null;
    'total'?: number;
}

