/* tslint:disable */
/* eslint-disable */
/**
 * Daney API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface APIDaneyRepositoriesEntitiesServerKeyRequester {
    'GuildID'?: number | null;
    'UID'?: string;
    'Value'?: any | null;
}

