/* tslint:disable */
/* eslint-disable */
/**
 * Daney API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MicrosoftAspNetCoreMvcRenderingSelectListGroup } from './microsoft-asp-net-core-mvc-rendering-select-list-group';

export interface MicrosoftAspNetCoreMvcRenderingSelectListItem {
    'Disabled'?: boolean;
    'Group'?: MicrosoftAspNetCoreMvcRenderingSelectListGroup;
    'Selected'?: boolean;
    'Text'?: string | null;
    'Value'?: string | null;
}

